### ISSUE TITLE
Email retete

### ISSUE THREAD

**Issue by auratoth** [gsuveti/diy-tutorials#21]
1. Cand primesti email: in loc de DIY Tutorials sa apara LucrareaMea si la subiect Lucrare DIY - numele lucrarii
2. Arunca tot textul cu masuratori si poze, dar pozele trebuie sa fie mici in line with text (ca sa nu ocupe spatiu degeaba in mail)
3. Produsele pot fi aruncate separat intr-un pdf tabelar:
    poza, denumire, cantitate
    astfel incat produsele selectate sa incapa intr-o pagina in caz de print
    iar la sfarsitul textului de reteta sa apara pur si simplu "Vezi fisierul atasat cu produsele necesare pentru lucrarea ta"
4. m-am intors in reteta si am adaugat un produs optional (probabil a deselectat pachetul ales) si am primit mail doar cu produsul optional adaugat ultima data (poza mare si cantitate) atat, nimic text

**Comment by gsuveti** [comment]
- show link to tutorial
- remove content
- add footer
